version: '3.1'

services:

  wordpress:
    depends_on:
      - mysql
    build:
      context: ./dockerfiles/Wordpress
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_test
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* enabling language & saving to */
        define('FS_METHOD','direct');
        define( 'WP_DEBUG', true );
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/myEvent

  cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    # This is required to run wordpress-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
      # The sleep 15 is required so that the command is run after
      # mysql is initialized. Depending on your machine this might take
      # longer or it can go faster.
    command: >
        /bin/sh -c '
        sleep 15;
        wp core install --path="/var/www/html" --url="http://localhost" --title="Local Wordpress By myEvent" --admin_user=admin --admin_password=password --admin_email=darek@darek.com  --allow-root;
        wp language core install pl_PL;
        wp language core activate pl_PL;
        wp core update;
        wp i18n make-pot . languages/my-event-lang.pot --domain=my-event-lang;
        '
    # add shared volumes
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/myEvent

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example

  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp

  composer:
    image: composer
    volumes:
      - .:/app

volumes:
  testsuite:
  wordpress:
  .:
